### ISSUE TITLE
serialized error has `pluginsOpts` property although it should be removed in `afterSerialize`

### ISSUE THREAD

**Issue by benkroeger** [ehmicky/modern-errors-serialize#12]
### Guidelines

- [X] Please search other issues to make sure this bug has not already been reported.
- [X] If this is related to a typo or the documentation being unclear, please click on the relevant page's `Edit` button (pencil icon) and suggest a correction instead.

### Describe the bug

I believe [this](https://github.com/ehmicky/modern-errors-serialize/blob/7f47432e31c2c3140938af8090f86da0be95de3c/src/serialize.js#L54) code intends to remove the `pluginsOpts` property from the serialized error object.
However, `error-serializer` always returns the object that would be passed to `afterSerialize` as the second object (see [serializeDeep](https://github.com/ehmicky/error-serializer/blob/7b2d823abdfba64ee41c3fa47d1ceea1d39a55c0/src/serialize.js#L23) and [serializeShallow](https://github.com/ehmicky/error-serializer/blob/7b2d823abdfba64ee41c3fa47d1ceea1d39a55c0/src/serialize.js#L36)).
So I believe extending this package's implementation of `afterSerialize` to remove the prop from the second function arg would actually do what was intended.

### Steps to reproduce

1. create error class according to documentation
2. load this plugin
3. create error
4. log error
5. see that the output includes `pluginsOpts`

### Configuration

none

### Environment

  System:
    OS: macOS 14.5
    CPU: (16) arm64 Apple M3 Max
    Memory: 1.35 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/Library/pnpm/node
    npm: 10.5.0 - ~/Library/pnpm/npm
    pnpm: 9.1.4 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.5
  npmPackages:
    modern-errors-serialize: ^6.0.0 => 6.0.0 

### Pull request (optional)

- [X] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @benkroeger,

Thanks for reaching out.

When serializing an error, its plugin options are kept. This is good since it allows you to keep any plugin options if you were to re-create the error by parsing it. 

To do this, the plugin options are kept under a `.pluginsOpts` property in the serialized object. That property is only defined when you defined some plugin options.

If this is not desired though, you can now use the `{exclude: ['pluginsOpts']}` option, since [`6.1.0`](https://github.com/ehmicky/modern-errors-serialize/releases/tag/6.1.0).

**Comment by benkroeger** [comment]
Hi @ehmicky , thanks for quickly implementing that new feature. I was however wondering why you would [call](https://github.com/ehmicky/modern-errors-serialize/blob/7f47432e31c2c3140938af8090f86da0be95de3c/src/serialize.js#L56)

```js
delete error.pluginsOpts
```

if the intention was to keep it in there. My understanding is that the linked code "only" modifies the wrong `error` object. it is supposed to operate on the second argument to that function.

**Comment by ehmicky** [comment]
This specific line of code was removed [from the last version](https://github.com/ehmicky/modern-errors-serialize/blob/main/src/serialize.js). The intention should be clearer with the new implementation.
