### ISSUE TITLE
Can we (optionally) remove the `stack` prop from serialized error?

### ISSUE THREAD

**Issue by benkroeger** [ehmicky/modern-errors-serialize#13]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

When serializing an error to prepare it for API response, I'd like the response to the client NOT to include the `stack` information of said error

### Describe the solution you'd like

optionally also removing `stack` in `afterSerialize`
Plugin options or even invocation options could somehow be derived in [serializeValue](https://github.com/ehmicky/modern-errors-serialize/blob/7f47432e31c2c3140938af8090f86da0be95de3c/src/serialize.js#L13)

### Pull request (optional)

- [X] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @benkroeger,

Great idea! You can now use the `{exclude: ['stack']}` option to achieve this.

```js
const ExampleError = BaseError.subclass('ExampleError', {
  serialize: { exclude: ['stack'] },
})
const error = new ExampleError('example')

const errorObject = ExampleError.serialize(error)
console.log(errorObject.stack) // undefined
console.log(errorObject) // { name: 'Error', message: 'example' }
```

Please check out the release notes of [`6.1.0`](https://github.com/ehmicky/modern-errors-serialize/releases/tag/6.1.0) for more details.

**Comment by ehmicky** [comment]
@all-contributors Could you please add @benkroeger for ideas?
